/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Description } from "./description";

// @ts-ignore
export function descriptionTemplateHtml(this: Description) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return (_vm.notEmpty || _vm.message)?_c('p',{class:_vm.theme.help},[_vm._v(_vm._s(_vm.message))]):_vm._e()}
// tslint:enable
