/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Icon } from "./icon";

// @ts-ignore
export function iconTemplateHtml(this: Icon) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('button',{class:_vm.theme.button,on:{"click":function($event){_vm.$emit('click')}}},[(_vm.icon.isText)?_c('span',[_vm._v(_vm._s(_vm.text))]):_c('i',{class:_vm.text})])}
// tslint:enable
