/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { JSONEditor } from "./index";

// @ts-ignore
export function indexTemplateHtml(this: JSONEditor) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('editor',{attrs:{"schema":_vm.schema,"initial-value":_vm.initialValue,"theme":_vm.themeObject,"locale":_vm.localeObject,"icon":_vm.iconObject,"readonly":_vm.readonly,"required":true,"dragula":_vm.dragula,"md":_vm.md,"hljs":_vm.hljs,"forceHttps":_vm.forceHttps},on:{"update-value":function($event){_vm.updateValue($event)}}})}
// tslint:enable
