/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { NullEditor } from "./null-editor";

// @ts-ignore
export function nullEditorTemplateHtml(this: NullEditor) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{class:_vm.theme.row},[_c('label',{class:_vm.theme.label},[_vm._v(_vm._s(_vm.titleToShow)),_c('div',{class:_vm.theme.buttonGroup,style:(_vm.buttonGroupStyle)},[_c('optional',{attrs:{"required":_vm.required,"value":_vm.value,"isReadOnly":_vm.isReadOnly,"theme":_vm.theme,"locale":_vm.locale},on:{"toggleOptional":function($event){_vm.toggleOptional()}}}),(_vm.hasDeleteButtonFunction)?_c('icon',{attrs:{"text":_vm.icon.delete,"theme":_vm.theme,"icon":_vm.icon},on:{"click":function($event){_vm.$emit('delete')}}}):_vm._e()],1)]),_c('description',{attrs:{"theme":_vm.theme,"message":_vm.schema.description}})],1)}
// tslint:enable
