/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { NumberEditor } from "./number-editor";

// @ts-ignore
export function numberEditorTemplateHtml(this: NumberEditor) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{class:_vm.errorMessage ? _vm.theme.errorRow : _vm.theme.row},[_c('label',{class:_vm.theme.label},[_vm._v(_vm._s(_vm.titleToShow)),_c('div',{class:_vm.theme.buttonGroup,style:(_vm.buttonGroupStyle)},[_c('optional',{attrs:{"required":_vm.required,"value":_vm.value,"isReadOnly":_vm.isReadOnly,"theme":_vm.theme,"locale":_vm.locale},on:{"toggleOptional":function($event){_vm.toggleOptional()}}}),(_vm.hasDeleteButtonFunction)?_c('icon',{attrs:{"text":_vm.icon.delete,"theme":_vm.theme,"icon":_vm.icon},on:{"click":function($event){_vm.$emit('delete')}}}):_vm._e()],1)]),(_vm.useInput)?_c('input',{class:_vm.theme.formControl,attrs:{"type":"number","readOnly":_vm.isReadOnly,"disabled":_vm.isReadOnly},domProps:{"value":_vm.value},on:{"change":function($event){_vm.onChange($event)},"keyup":function($event){_vm.onChange($event)}}}):_vm._e(),(_vm.useSelect)?_c('select2',{attrs:{"data":_vm.options,"value":_vm.value},on:{"update":function($event){_vm.updateSelection($event)}}}):_vm._e(),_c('description',{attrs:{"theme":_vm.theme,"message":_vm.schema.description}}),_c('description',{attrs:{"theme":_vm.theme,"message":_vm.errorMessage}})],1)}
// tslint:enable
