/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Optional } from "./optional";

// @ts-ignore
export function optionalTemplateHtml(this: Optional) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return (_vm.hasOptionalCheckbox)?_c('div',{class:_vm.theme.optionalCheckbox},[_c('label',[_c('input',{attrs:{"type":"checkbox","disabled":_vm.isReadOnly},domProps:{"checked":_vm.value === undefined},on:{"change":function($event){_vm.$emit('toggleOptional')}}}),_vm._v(" "+_vm._s(_vm.locale.info.notExists))])]):_vm._e()}
// tslint:enable
